#!/bin/bash

# TODO:
# Extend this script to receive commands in this way:
# ./integrate quote/form dev where:
# quote/form is the branch to merge, and;
# dev is the parent branch.

echo -n "Merging to master..."
git checkout master || exit
git merge $1
echo "ok"

# Don't do this unless master is the parent branch

echo -n "Pushing to origin..."
git push origin master
echo "ok"

git checkout $1
